name: "Dependency Review"
on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-Review:
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@main
    with:
      public: true
      distributed: true
