name: "Dependency Review"
on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  dependency-Review:
    uses: coveo/public-actions/.github/workflows/dependency-review.yml@master
    with:
      public: true
      distributed: true
