name: "Security Scan"

on:
  schedule:
    - cron: "17 2 * * 2"
  workflow_run:
    workflows:
      - CD
    types:
      - completed
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize, reopened]

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
